<template>
  <q-page class="flex flex-center">
    <img class="img"
      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRs256gFD5q-xYlooSkQcHRkGNTlU0KMxk3A&usqp=CAU"
      style="width: 200px; height: 200px">

    <p class="flex flex-center" style="width: 200px; height: 200px">"Student Management System (SMS) is a solution tool
      that is designed to
      track, maintain and manage all the data
      generated by a School, including the grades of a student, their attendance, their interpersonal activities
      records,
      etc.,</p>


  </q-page>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'IndexPage'
})
</script>
